#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
#redirect_me
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "54i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
