#!/usr/bin/env bash
# Bash script displaying "Best School" 10 times but includes "Hi" on the 9th

m=1
while [ $m -le 10 ]
do
	echo "Best School"
	if [ $m -eq 9 ]
	then
		echo "Hi"
	fi
	m=$(( m+=1 ))
done
