#!/usr/bin/env bash
# Bash script that loops through 1 to 10
# displays "bad luck" for the 4th loop iteration
# displays "good luck" for the 8th loop iteration
# displays "Best School" for the other iterations

m=1
while [ $m -le 10 ]
do
	if [ $m -eq 4 ]
	then
		echo "bad luck"
	elif [ $m -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( m+=1 ))
done
