#!/usr/bin/env bash
# Configurations

# Apache2 config
pkill apache2

if grep -q "listen \[::\]:80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen \[::\]:80/listen \[::\]:8080/" /etc/nginx/sites-available/default
fi
if grep -q "listen 80" /etc/nginx/sites-available/default ; then
    sed -i "s/listen 80/listen 8080/" /etc/nginx/sites-available/default
fi

chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Starting nginx
sudo -u nginx service nginx start
